export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const LOADING_FAILURE = 'LOADING_FAILURE';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';
export const SET_CURRENT_PAGE ='SET_CURRENT_PAGE';
export const SET_BUTTONS_PER_PAGE ='SET_BUTTONS_PER_PAGE';
export const SET_INDEX_FIRST_PAGE='SET_INDEX_FIRST_PAGE';